# 批量任务清单
jobs:
  - name: dapo-8k-train_bsz64-ppo_bsz64-rollout_n8-pp
    bash_path: /fs-computility/llm_fudan/lvhuijie/my_git_repo/verl/lhj_scripts/redundancy/qwen3-4b/dapo_math/DAPO/dapo-8k-train_bsz64-ppo_bsz64-rollout_n8_pp.sh
    nnodes: 4
    n_gpus_per_node: 8
    output_dir: /fs-computility/llm_fudan/lvhuijie/my_git_repo/verl/checkpoints_verl/redundancy/qwen3-4b/dapo_math/DAPO/dapo-8k-train_bsz64-ppo_bsz64-rollout_n8-process_reward-pp
